export enum Turn {
  MY,
  OPPONENT,
}

export const idHandPictures: DynamicObject<string> = {
  1: '../../../../assets/Photoes/hearth.png',
  2: '../../../../assets/Photoes/FieldPictures/yellowCircle.png',
};

export const idMoneyCollectorPictures: DynamicObject<string> = {
  0: '/',
  1: '../../../../assets/Photoes/hearth.png',
  2: '../../../../assets/Photoes/FieldPictures/yellowCircle.png',
};

export interface DynamicObject<T> {
  [key: string]: T;
}

export const field: any[][] = [
  [
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 7,
      health: 11,
      attackSpeed: 16,
      evasion: 0.3,
      moveSpeed: 5,
      cost: 4,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
  [
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 0,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 1,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
    {
      name: 2,
      attack: 6,
      health: 10,
      attackSpeed: 15,
      evasion: 0.2,
      moveSpeed: 4,
      cost: 3,
    },
  ],
];
