export enum Pages {
  MAIN_PAGE = 'MAIN_PAGE',
  DEVELOPERS_PAGE = 'DEVELOPERS_PAGE',
  GAME_PAGE = 'GAME_PAGE',
  THIRD_PAGE = 'THIRD_PAGE',
  AUTHORIZATION_PAGE = 'AUTHORIZATION_PAGE',
}
export enum GamePhases {
  PREPARING = 'PREPARING',
  START_GAME = 'START_GAME',
  FINISH_GAME = 'FINISH_GAME',
}

export enum IsGuest {
  NOT_GUEST = 'NOT_GUEST',
  GUEST = 'GUEST',
}

export enum GameState {
  NOPROCESS,
  PROCESS,
}
