export enum Pages {
  MAIN_PAGE = 'MAIN_PAGE',
  DEVELOPERS_PAGE = 'DEVELOPERS_PAGE',
  GAME_PAGE = 'GAME_PAGE',
  THIRD_PAGE = 'THIRD_PAGE',
}
export enum GamePhases {
  PREPARING = 'PREPARING',
  START_GAME = 'START_GAME',
  FINISH_GAME = 'FINISH_GAME',
}
